package com.capstone.transaction.controller;

import com.capstone.common.dto.ApiResponse;
import com.capstone.common.dto.TransactionRequest;
import com.capstone.common.dto.TransactionResponse;
import com.capstone.common.exception.ResourceNotFoundException;
import com.capstone.transaction.entity.postgres.LedgerMutationAudit;
import com.capstone.transaction.interceptor.TransactionIdInterceptor;
import com.capstone.transaction.service.TransactionService;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;
import java.util.UUID;

/**
 * Ledger mutation endpoints.
 *
 * txnType in TransactionRequest drives routing to
 * withdraw/deposit/transfer.
 *
 * TransactionIdInterceptor generates or captures the transaction UUID
 * before this controller method executes.
 */
@RestController
@RequestMapping("/api/v1/ledger")
@RequiredArgsConstructor
public class TransactionController {

    private final TransactionService transactionService;

    /**
     * Single entry point:
     * client sets request.txnType to
     * WITHDRAWAL | DEPOSIT | TRANSFER.
     *
     * The transaction UUID is supplied by TransactionIdInterceptor.
     */
    @PostMapping("/mutate")
    public ResponseEntity<ApiResponse<TransactionResponse>> mutate(
            @Valid @RequestBody TransactionRequest request,
            HttpServletRequest httpRequest) {

        String transactionId =
                (String) httpRequest.getAttribute(
                        TransactionIdInterceptor.TRANSACTION_ID_ATTRIBUTE);

        if (transactionId == null || transactionId.isBlank()) {
            throw new IllegalStateException(
                    "Transaction ID was not generated by the interceptor");
        }

        UUID txnId;

        try {
            txnId = UUID.fromString(transactionId);
        } catch (IllegalArgumentException ex) {
            throw new IllegalStateException(
                    "Invalid transaction ID generated by interceptor",
                    ex);
        }

        TransactionResponse response =
                switch (request.txnType()) {

                    case "WITHDRAWAL" ->
                            transactionService.withdraw(
                                    request,
                                    txnId);

                    case "DEPOSIT" ->
                            transactionService.deposit(
                                    request,
                                    txnId);

                    case "TRANSFER" ->
                            transactionService.transfer(
                                    request,
                                    txnId);

                    default ->
                            throw new IllegalArgumentException(
                                    "Unsupported txnType: "
                                            + request.txnType());
                };

        return ResponseEntity.status(HttpStatus.CREATED)
                .body(
                        ApiResponse.ok(
                                request.txnType()
                                        + " processed",
                                response));
    }

    /**
     * Returns all ledger_mutation_audit rows for a given transaction.
     *
     * WITHDRAWAL → 1 row (DEBIT)
     * DEPOSIT    → 1 row (CREDIT)
     * TRANSFER   → 2 rows (DEBIT + CREDIT)
     */
    @GetMapping("/audit/{txnId}")
    public ResponseEntity<ApiResponse<List<LedgerMutationAudit>>> getAudit(
            @PathVariable("txnId") String txnId) {

        List<LedgerMutationAudit> audits =
                transactionService.findAuditByTxnId(txnId);

        if (audits.isEmpty()) {
            throw new ResourceNotFoundException(
                    "Transaction " + txnId + " not found");
        }

        return ResponseEntity.ok(
                ApiResponse.ok(audits));
    }
}